export const FETCH_QUESTIONS_REQUEST = "FETCH_QUESTIONS_REQUEST";
export const FETCH_QUESTIONS_SUCCESS = "FETCH_QUESTIONS_SUCCESS";
export const FETCH_QUESTIONS_FAIL = "FETCH_QUESTIONS_FAIL";

export const SET_CURRENT_QUESTION = "SET_CURRENT_QUESTION";
export const SAVE_ANSWER = "SAVE_ANSWER";
export const MARK_FOR_REVIEW = "MARK_FOR_REVIEW";
export const SUBMIT_EXAM = "SUBMIT_EXAM";

